spring:
  application:
    name: Restaurant
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 2007
security:
  secret:
      key: none
